os:
- linux
services:
- docker
language: node_js
node_js:
- 6.10.0
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=6.10.0
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add bower gulp-cli
install:
- yarn install -f
script:
- chmod +x mvnw
- "./mvnw clean test"
- gulp test
- "./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy -DskipTests -Pprod -Dheroku.appName="
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  api_key:
    secure: c9SqlFiLWbqqUNrJo+l3OFXB7HcmSpWN6rw+5OXgGgw0wym+FsRkAp39NGV5QSrtJFckeI1WgTbRIoi5OVJFxm3ztVnu5QqrbzEvctYNtjtLyGBB6XXw9ZrhJ2Uvq2EOqOnqzkeZ6vqPAFBj9rvdwy8YyNN4hrD1Ik58ZCFu6kCDZwaNJrwGpyPfC8/aIc7WrQuYMDfYKQQ/P6C6d7m77e9sZYnTM76lUCd3E48Kf6zBTqZ1b7z7ROXhGtZLYJin++m/TQ6Z/Q3XKUDjOuzOF/FRpmlmf/zgzpqLbEadbJvlc8it16QjeXlmC7wEoD7FtSMG5wmx//O6VmIHeAgZVjtySoTPcpJ16jYt6ZBtV3RoG8Uc56BCK3oGc5SDSjbyj8iJIc863Poa2pnwJuRnAPfHY8aqwyCpQQt7dTI607emieVGvtgL6eDABdPP7Mr/qmHdjI/IgLevp5HqeybLVsWfipM7W9JfOpIc2kgGBh9i/JS0r4uzJG5+U5Xt4zLkfwWw5xjIDlZ2Dd88nvoh/YsEyocxUK4T3wkI4SEoMcKdDajxP4ALTflENSjiJtnELPSQg1l2asnl66KLXm0bsSEJhWVmlIssgL2biWuy7jlDTBn0hfM5Y9LJF60XRHcdk0ZXhn9GYScOjNutpFHQtuJVSQ3HE7nHSGzG6wPUbWQ=
